Update the description of `rustc-dep-option-generator`
rust-lang-ja/atcoder-rust-resources pull request #11
Opened 2019-11-29 18:03 UTC by qryxip

rust-lang-ja/atcoder-rustc-dep-option-generator#2

2019-11-30 17:14 UTC, statiolake commented
ありがとうございます。先に申し上げておきますが、CLIツールとしてはとても使いやすくなるよい改善をいただいたと思っています。ですがこれをマージするかどうか少し迷っています。というのも、このツールにおいては実装が単純で動作が軽量・シンプルであることが特に重要だと考えているからです。たとえばワークスペースの自動コンパイル機能は必要ないかなと考えています。またstructopt等によるベターなハンドリングも、このツールに限っては今後オプショナルな引数を増やす必要がでてきてからでいいかな (そしてその必要性が出てくることはあまりないかな) と考えています。

このように考えるのは、もともとこのツールを作成したときに次のことを念頭に置いていたからです。

- Rustをあまり知らなくても読めば動作がある程度把握できるツールであること。
  これは元々がCargoのブラックボックスさに起因する動作がよく分からない問題を解決するために作ったものだからです。加えて、 (当初は提出ごとに実行する前提だったため; 後述) 提出内容に影響するような不正なプログラムでないことを比較的簡単に検証できるようにするためです。
- 実行が軽量で、必要十分なことしかしないこと。
  もともとこのツールはAtCoderの1提出をコンパイルするごとに毎回実行してオプションを生成する前提でした。コンパイル時、ひいては実行時のマシン環境を判別してavxなどに対応するオプションを自動生成することで高速化を図ることも視野にいれていたためです。bookの対応箇所は以下のようになっていたかと思いますが、ここで`$()`を使って毎回実行するような記述になっているのはその際の名残りです。その後、今回はその手の最適化を入れない方針であろうことが分かったためにそれらのオプションを生成することは止め、であれば生成されるコンパイルオプションは実行環境には影響されないから毎回実行する必要はない、ということをbookに追加しました。
> コンパイルコマンドは以下のとおりです。
> 
> ```
> $ cd $HOME/WORKAREA
> $ RUST_LIB=$RUST_HOME/lib
> $ rustc --edition=2018 -C opt-level=3 \
>     $(rustc-dep-option-generator $RUST_LIB/Cargo.toml $RUST_LIB/target/release/deps) \
>     main.rs
> ```
>
> なおrustc-dep-option-generatorの出力は実行環境やソースには依らず、単に依存クレートの位置のみに依ります。従ってインストール時に先にrustc-dep-option-generatorを単体で実行し、その出力を直接コンパイルオプションとして置き換えても問題ありません。こうすると毎回コンパイルのたびにこのツールを実行する必要がありません。

とはいえ、今後マラソンの扱いや最適化に関する方針が見直されたとしたら、これらの最適化をもう一度考慮することになるかもしれません。それまでの間は利便性をとって自動コンパイル機能その他を有効にしたとしてもこの時に再び軽量な動作に戻すのであれば、現段階で機能に問題があるわけではない以上はこのままにしておいてもよいのかなと考えます。

また自動コンパイル機能は確かに便利ではありますが、先だって`cargo build --release`しておけば済む話ではありますし、一旦導入するライブラリが定まってしまえばそうそうCargo.tomlを書き換える (リビルドが必要になる) こともないのかなと思います。むしろこのツールを実行するとライブラリ部分がもしかしたら書き変わるかもしれない、となれば、ツールを使うたびにライブラリの一部が勝手に書き変わってしまわないかなどを意識する必要が生じ、 (たとえば念のためプロジェクトをコピーしてその上で実行するようにするなど) 結果として使いたいときに気軽には使い辛くなってしまうかもしれません。

小さく軽量なツールであれば依存関係も少なくて済み、コンパイル時間も短くすむということも一応メリットとしてあります。このツールは人間が実行するのは初回セットアップ時に多くても数回程度で、あとはオプションをスクリプトに直貼りしてしまうかコマンドを`$()`の形で埋め込んでスクリプトから呼び出されるかもしれない程度と見込んでいます。ですので、表示が分かりやすかったり、実行するのが簡単だったりするメリットよりも、上に挙げたようなことによるメリットの方が大きいのではないかと考えています。

以上長々と失礼しましたが、なんとなく考えていることです。もう少し考えてみますが、何か私に見落しなどあればぜひ。

2019-12-06 13:17 UTC, statiolake requested changes
rustc-dep-option-generator の方が完結したらこちらもマージしようと思っていて、忘れていました。多少の機能変更があったので少し合わなくなっている部分がありそうです。確認お願いします。

2019-12-06 13:17 UTC, statiolake commented on src/atcoder-env/installing-rustc-dep-option-generator.md
> +なお`libssl-dev`は`rustc-dep-option-generator`が`cargo`をライブラリとして用いているために必要です。
いちおう自動アップデート機能は追加しないことにしたので、ネットワークアクセスが不要という文言は残しておいてよいかと。

```suggestion
なお`libssl-dev`は`rustc-dep-option-generator`が`cargo`をライブラリとして用いているために必要ですが、このツールではその機能は使いません。ツール実行時のネットワーク・アクセスは不要です。
```

2019-12-06 13:17 UTC, statiolake commented on src/atcoder-env/installing-rustc-dep-option-generator.md
> +    Finished release [optimized] target(s) in 0.06s
このあたりの出力も変わってくるかと思います。 (Suggestion は単一行にしかつけられないのですね...)

2019-12-06 18:05 UTC, qryxip commented on src/atcoder-env/installing-rustc-dep-option-generator.md
> +    Finished release [optimized] target(s) in 0.06s
これでどうでしょうか。

2019-12-06 18:19 UTC, statiolake commented
よさそうです、ありがとうございます！

2019-12-06 18:20 UTC, merged